feat: allow to set default profile
aave/lens-protocol pull request #27
Opened 2022-02-25 12:39 UTC by joshstevens19

With wallet being able to follow and collect as the main ethos of this protocol you do hit some UI/UX issues when trying to display this to the users. Their wallet in theory does not hold any primary identity info about the user itself. 

This PR goes down the ethos of what ENS does as they have the same issue, you can own many ENS but you want to display a default. 

Exposing a way of allowing you to map a default profile identity to your wallet address will allow UIs ability to show the default profile when someone collects or follows if it is mapped. 

This is then tying into your web3 identity as a profile could be seen as your identity which you use throughout the web3 space. Attached to that is information about yourself which I think is super powerful.

2022-02-25 12:44 UTC, damarnez commented
Wow, great feature! This would simplify the flow a lot and solve a lot of issues with the profile.

2022-02-25 12:55 UTC, EthWarrior commented
Love it. It really helps also to manage your followings - for example you might want to use a separate profile to follow creators in another application but want to have it linked into your default profile.

2022-02-25 13:46 UTC, nicolost commented
Awesome! This is also going to be really important as users start to follow each other and want to zoom out to see the social graph at a high level e.g. showing UserX follows UserY 😁

2022-02-28 15:59 UTC, miguelmtzinf requested changes

2022-03-02 12:59 UTC, miguelmtzinf commented on contracts/core/LensHub.sol
> +            _validateCallerIsProfileOwner(profileId, wallet);
think you should do this validation in both cases
would be nice to add a test case

2022-03-02 16:56 UTC, joshstevens19 commented
this will go on v1 mainnet release!

2022-03-02 16:56 UTC, merged