fix: Prevent Treasury Transfers if the Treasury Fee Is Zero
aave/lens-protocol pull request #77
Opened 2022-03-22 17:45 UTC by Zer0dot

This PR prevents transfers to the treasury if the computed treasury fee amount is zero. Note that this still includes the treasury fee computation as, in cases with very few decimals, it's possible the treasury fee amount is zero even if the treasury fee BPS is non-zero.

2022-03-22 17:49 UTC, donosonaumczuk requested changes
Lets add some test to check does not fail when treasury fee is zero for ERC20s than fails on zero-amount transfers

2022-03-22 19:47 UTC, donosonaumczuk submitted a review, later dismissed

2022-03-22 20:21 UTC, Zer0dot commented
@miguelmtzinf can you review as well

2022-03-22 21:19 UTC, Zer0dot commented
Also missing a bit of coverage on the test front, do not merge yet.

2022-03-23 18:13 UTC, donosonaumczuk approved these changes

2022-03-23 18:17 UTC, merged